// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/waiting": {
    params: {};
  };
  "/game": {
    params: {};
  };
  "/complete": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/waiting" | "/game" | "/complete";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/waiting.tsx": {
    id: "routes/waiting";
    page: "/waiting";
  };
  "routes/game.tsx": {
    id: "routes/game";
    page: "/game";
  };
  "routes/complete.tsx": {
    id: "routes/complete";
    page: "/complete";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/waiting": typeof import("./app/routes/waiting.tsx");
  "routes/game": typeof import("./app/routes/game.tsx");
  "routes/complete": typeof import("./app/routes/complete.tsx");
};